# Generated by Django 5.2 on 2026-02-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='census',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='census',
            constraint=models.UniqueConstraint(fields=('voting_id', 'voter_id'), name='unique_voting_voter'),
        ),
    ]
