version: '3.4'

services:
  db:
    restart: always
    container_name: decide_db
    image: pgautoupgrade/pgautoupgrade:14-alpine3.21
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - decide
    env_file:
      - .env.postgres
  web:
    restart: always
    container_name: decide_web
    image: decide_web:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    expose:
      - "5000"
    volumes:
      - static:/app/static
    depends_on:
      - db
    networks:
      - decide
    env_file:
      - .env.decide
  nginx:
    restart: always
    container_name: decide_nginx
    image: decide_nginx:latest
    build:
        context: .
        dockerfile: Dockerfile-nginx
    volumes:
      - static:/app/static
    ports:
      - "8000:80"
    depends_on:
      - web
    networks:
      - decide

volumes:
  static:
    name: decide_static
  db:
    name: decide_db

networks:
  decide:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
